server {
    listen 8081;
    server_name kupi.350str.nomorepartiessite.ru;

    location / {
        root /usr/share/nginx/html;
        index index.html index.html;
        # Исправляем роутинг на фронтенде
        try_files $uri $uri/ /index.html;
    }
}